version: "3.8"

services:
  ros2_jazzy:
    build: .  # Uses the Dockerfile in the current directory
    container_name: ros2_jazzy
    environment:
      - DISPLAY=172.30.144.1:2
      - QT_X11_NO_MITSHM=1  # Prevents X11 shared memory issues
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # X11 forwarding for GUI apps
    stdin_open: true  # Keeps STDIN open (interactive mode)
    tty: true         # Enables terminal support
    networks:
      - ros_network


  # foxglove to visualize live data 
  foxglove_bridge:
    build:
      context: ./foxglove_bridge/
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    container_name: foxglove_bridge
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765
    networks:
      - ros_network
  
  caddy:
    image: caddy:latest
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:80"
      - "8443:443"
      - "8443:443/udp"
    volumes:
      - /home/multimico/robogardener/docker_container_robogardener/container_ros2_jazzy/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ros_network

networks:
  ros_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
