version: '3.8'

services:
  plant_monitor:
    image: ros:jazzy-arm64-desktop
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # LiDAR
      - "/dev/ttyACM0:/dev/ttyACM0"  # Motor
      - "/dev/video0:/dev/video0"     # Camera
    volumes:
      - /home/pi/calib_images:/calib_images
    command: /bin/bash
    stdin_open: true
    tty: true
