version: '3.8'

services:
  plant_monitor:
    image: ros:jazzy-arm64-desktop
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # LiDAR
      - "/dev/ttyACM0:/dev/ttyACM0"  # Motor
    volumes:
      - home/pi/digital_twin_plants:/ros2_ws/src/digital_twin_plants  # Mount into src directory
    environment:
      - ROS_HOSTNAME=localhost
    command: /bin/bash
    stdin_open: true
    tty: true