version: '3.8'

services:
  plant_monitor:
    image: ros:jazzy-arm64-desktop
    privileged: true
    network_mode: "host"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/video0:/dev/video0"
    command: /bin/bash
    stdin_open: true
    tty: true

  image_api:
    build: ./image_api
    ports:
      - "6000:6000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
