services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_jazzy_desktop
    volumes:
      - ${REPO_PATH}:/ros_ws/src/digital_twin
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
    network_mode: host
