services:
  ros2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ros2_jazzy_desktop
    volumes:
      - ${REPO_PATH}:/ros_ws/src/digital_twin
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    #devices:
    #  - /dev/dri:/dev/dri
    networks: 
      - ros_network

  traefik:
      image: traefik:v3.1.2
      command:
        - "--api.insecure=true" # Enable Traefik dashboard (for development purposes)
        - "--providers.docker=true" # Enable Docker as a provider
        - "--entrypoints.web.address=:80" # Define an entrypoint for HTTP traffic
        - "--entrypoints.websecure.address=:443" # Define an entrypoint for HTTPS traffic
        - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
        - "--certificatesresolvers.myresolver.acme.email=grahanoi@students.zhaw.ch"
        - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      ports:
        - "81:80" # Expose HTTP
        - "8081:8080" # Expose Traefik dashboard
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock # Allow Traefik to access Docker
        - ./letsencrypt:/letsencrypt
      networks:
        - ros_network

  foxglove_bridge:
      build:
        context: .
        dockerfile: Dockerfile_foxglove
      ports:
        - 8765:8765
      container_name: foxglove_bridge
      command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765
      networks:
        - ros_network
      labels:
        - "traefik.http.routers.foxglove.rule=Host(`${DOMAIN}`)"
        - "traefik.http.services.foxglove.loadbalancer.server.port=8765"
networks:
  ros_network:
    driver: bridge